fix: double colon route issue (#219)
delvedor/find-my-way pull request #220
Opened 2021-12-20 17:31 UTC by bugagashenkj

Hi, please don't judge me too hard since it's my first contribution here. I think the problem is that the `parametricBrother` field can be set even if `child.prefix` starts with `":"`. In this case, these are two colons in a row, which should be parsed as a simple path, and not as a path with a parameter. I'm not sure that it's the best solution, but it works, so I decided to create a PR.

2021-12-20 17:35 UTC, RafaelGSS requested changes
Would you mind adding tests to your fix?

2021-12-21 17:38 UTC, RafaelGSS approved these changes
Great work!

2021-12-23 13:44 UTC, bugagashenkj commented
Fixed #222. I added changes to this PR because they were fixed in the same place.

2021-12-23 13:48 UTC, mcollina approved these changes
lgtm

2021-12-23 13:48 UTC, mcollina commented
we are waiting for a review & release from @delvedor

2021-12-23 15:38 UTC, delvedor approved these changes
LGTM

2021-12-23 15:39 UTC, merged

2021-12-23 15:44 UTC, delvedor commented
Released in `v5.1.1` 🚀