Removed unnecessary constraints check
delvedor/find-my-way pull request #229
Opened 2021-12-30 12:06 UTC by bugagashenkj

It seems like it checks constraints twice: in the findMatchingChild function and in the find function.

2021-12-30 12:07 UTC, bugagashenkj commented
depends on #226

2021-12-30 12:50 UTC, bugagashenkj commented
### Benchmark results:
**Before (optimize-find-method, #226)**

<img width="876" alt="1" src="https://user-images.githubusercontent.com/31734731/147753268-cfa6177f-6bbe-47fe-8324-3451a183ad8b.png">

**After:**

<img width="878" alt="Снимок экрана 2021-12-30 в 14 44 45" src="https://user-images.githubusercontent.com/31734731/147753327-ca4f4228-18a9-45b2-9f66-bf049444efe2.png">

2021-12-30 12:50 UTC, bugagashenkj commented
The biggest increase in performance is when we have constraints.

2022-01-09 10:26 UTC, delvedor requested changes
Can you solve the conflicts first? It looks like some of this changes are already present in main, making this code harder to review.

2022-01-12 07:45 UTC, delvedor approved these changes
LGTM

2022-01-12 07:45 UTC, merged