Node insertion optimization
delvedor/find-my-way pull request #243
Opened 2022-03-28 20:54 UTC by bugagashenkj

As I mention this #242 wasn't the best solution to this #241 issue. This is much better. I needed to optimize the insert method first. The main idea of optimization is that previously the insertion of each node started at the root of the tree. Now, setting a new node is based on the previous one. This allowed us to simplify the code a lot.

2022-03-28 21:13 UTC, mcollina approved these changes
lgtm

2022-03-29 00:14 UTC, RafaelGSS reviewed
Can you share the benchmarks?

2022-03-29 08:10 UTC, delvedor requested changes
Nice! Can you share the benchmarks?

2022-03-29 09:15 UTC, bugagashenkj commented
**Main branch**

<img width="890" alt="Снимок экрана 2022-03-29 в 12 13 51" src="https://user-images.githubusercontent.com/31734731/160577796-fba2b487-8108-48ba-a46e-7057624f0fe7.png">

**Current branch**

<img width="883" alt="current" src="https://user-images.githubusercontent.com/31734731/160577858-3c2d2f68-b291-4e50-b467-fd936cc1df8d.png">

2022-04-05 12:49 UTC, delvedor approved these changes
LGTM

2022-04-06 10:35 UTC, mcollina commented
Could you rebase? Thanks!

2022-04-06 11:00 UTC, bugagashenkj commented
@mcollina #237 depended on this. Since you've merged it we, don't need to merge this anymore.

<img width="226" alt="image" src="https://user-images.githubusercontent.com/31734731/161960519-7a741fcc-11dc-49c1-9d13-1843b996ace9.png">

2022-04-06 11:02 UTC, closed without merging