Add router.off method support filter
delvedor/find-my-way pull request #251
Opened 2022-04-14 08:02 UTC by OrangeXC

2022-04-14 08:33 UTC, bugagashenkj requested changes

2022-04-14 08:33 UTC, bugagashenkj commented on index.js
> +      .every((key) => derivedConstraints[key] === currentConstraints[key])
Why do you check only keys and not check values?

2022-04-14 08:33 UTC, bugagashenkj commented on index.js
> +      .every((key) => derivedConstraints[key] === currentConstraints[key])
You should use deepEqual like here to compare constraints.
https://github.com/delvedor/find-my-way/blob/b38003a06b59da0ba336522babb933d465db3b96/custom_node.js#L207

2022-04-14 08:33 UTC, bugagashenkj commented on index.js
> +      return !(method === route.method && path === route.path && matcher(route.opts?.constraints))
The optional chaining operator only appeared in nodejs 14, we can't use it since we support the 12 version.

2022-04-15 09:30 UTC, bugagashenkj approved these changes
LGTM

2022-04-15 10:06 UTC, mcollina requested changes
Can you document this in the README?

2022-04-18 00:49 UTC, OrangeXC commented
> Can you document this in the README?

Done

2022-04-18 06:56 UTC, mcollina commented on README.md
> +Deregister a route for each `constraints` key is matched, containing keys like the `host` for the request, the `version` for the route to be matched, or other custom constraint values.
```suggestion
Deregister a route for each `constraints` key is matched, containing keys like the `host` for the request, the `version` for the route to be matched, or other custom constraint values. See the [constraints section](https://github.com/delvedor/find-my-way#constraints) to know more.
```

2022-04-18 08:14 UTC, mcollina approved these changes
lgtm

2022-04-18 09:11 UTC, mcollina commented
Still lgtm

2022-04-20 01:17 UTC, OrangeXC commented
@mcollina @bugagashenkj   

Can this PR be merged?

2022-04-20 21:42 UTC, mcollina commented
Unless @delvedor beats me to it, I've limited bandwidth to ship this in a release before May.

2022-04-24 13:34 UTC, Eomm approved these changes

2022-04-24 14:04 UTC, merged