Adding feature ignoreDuplicateSlashes with tests
delvedor/find-my-way pull request #270
Opened 2022-05-01 20:35 UTC by code-ape

## Overview
This is a PR for the feature discussed in https://github.com/delvedor/find-my-way/issues/240 which relates to expected behavior for duplicate slashes in path. It was stated this would be a welcome PR and @mcollina directed me to PR #50 for reference of implementing a similar feature.

## Related Issues & PRs

1. #240
2. #50

## Changes
1. Add support for config option `ignoreDuplicateSlashes` which will condense any continuous occurrence of `/` in the path into a single `/`.
2. Add tests for `ignoreDuplicateSlashes` following pattens of existing tests for `ignoreTrailingSlash`.
3. Basic documentation of this feature added to `README.md`.

2022-05-01 20:52 UTC, ivan-tymoshenko requested changes
Hi, thanks for your contribution. I guess the main idea was to not match the empty params, but not to remove duplicate slashes. I mean if someone decided to add a route with two slashes in a row we should match it.

Try to check if a parameter length is not equal to 0, how we check the maximum parameter length and see if it works. https://github.com/delvedor/find-my-way/blob/2608f2baf0ff6be19f2616bae8682ddfbd8f675b/index.js#L446

2022-05-01 20:52 UTC, ivan-tymoshenko commented on index.js
> +  return path.replace(/\/\/+/g, '/')
It's not a good idea to use regex matching in a find method. It's a hot path. You can run benchmarks to see the performance drop.

2022-05-01 22:01 UTC, code-ape commented
Hi @ivan-tymoshenko, thanks for the quick reply 😄

I think you may have misunderstood #240. I filed it a couple months ago and the desired functionality was to remove duplicate sequential `/`. This is common behavior for web servers, for example this works: https://github.com/delvedor//////find-my-way

You can check the code example which has paths like `/a///d` as test cases. I was opening this PR based on this comment which indicted it would be of interest: https://github.com/delvedor/find-my-way/issues/240#issuecomment-1058449629

And thanks for the callout on regex! I will replace that with a proper loop shortly for better performance 🚀

2022-05-02 12:54 UTC, code-ape commented
I did a hand coding of the method for removing duplicate slashes and a benchmark to compare it to Regex. All work for that has been pushed to this branch. Both seem to perform well and the regex appears to do better in more "real world" examples. Below is a run from my M1 MacBook Pro.

Slowest performing scenario seems to be ~150ns / function call or ~500 CPU clock cycles for a 40 character string, which comes to ~10 CPU cycles per character. Also note that "no-op" scenarios where there are no duplicate slashes (which is presumably the majority of paths that would be processed in the real world) appears to only ~3 CPU cycles per character! 😄

```
$ node ./bench-duplicate.js
[/a/b]
removeDuplicateSlashes(0)      x 96,554,737 ops/sec ±0.21% (296 runs sampled)
removeDuplicateSlashesRegex(0) x 39,600,222 ops/sec ±0.10% (295 runs sampled)

[/api/v1/myNamespace/myObject/action1] 
removeDuplicateSlashes(1)      x 12,750,900 ops/sec ±0.41% (292 runs sampled)
removeDuplicateSlashesRegex(1) x 25,132,656 ops/sec ±0.29% (295 runs sampled)

[/a//b]
removeDuplicateSlashes(2)      x 35,200,687 ops/sec ±0.21% (297 runs sampled)
removeDuplicateSlashesRegex(2) x 18,131,065 ops/sec ±0.49% (289 runs sampled)

[/api/v1/myNamespace/myObject//action1]
removeDuplicateSlashes(3)      x 9,241,756 ops/sec ±0.31% (293 runs sampled)
removeDuplicateSlashesRegex(3) x 15,398,355 ops/sec ±0.36% (290 runs sampled)

[/a///////////////////////b]
removeDuplicateSlashes(4)      x 12,526,865 ops/sec ±0.32% (292 runs sampled)
removeDuplicateSlashesRegex(4) x 15,384,914 ops/sec ±0.20% (295 runs sampled)

[/api/v1/myNamespace/myObject///////////////////////action1]
removeDuplicateSlashes(5)      x 5,976,074 ops/sec ±0.32% (293 runs sampled)
removeDuplicateSlashesRegex(5) x 13,493,742 ops/sec ±0.21% (291 runs sampled)

[/api//v1//myNamespace//myObject//action1]
removeDuplicateSlashes(6)      x 6,328,285 ops/sec ±0.23% (294 runs sampled)
removeDuplicateSlashesRegex(6) x 6,712,087 ops/sec ±0.18% (295 runs sampled)
```

2022-05-02 13:41 UTC, ivan-tymoshenko commented
Hmm, it looks like regex in that case works really faster. Can you provide `npm run bench:cmp:ci` command results?

2022-05-02 13:45 UTC, ivan-tymoshenko commented
Another issue I'm worried about is that we shouldn't modify a wildcard part of the path. You can see that we return a wildcard param without trimming the last slash.

2022-05-08 16:48 UTC, ivan-tymoshenko reviewed
@code-ape Hi, do you need any help? Can you remove non-regexp implementation and provide benchmark results?

2022-05-08 16:48 UTC, ivan-tymoshenko commented on lib/duplicate-slashes.js
> +function removeDuplicateSlashes (path) {
Can you remove this, since you discovered that the regexp version is working faster?

2022-05-08 16:48 UTC, ivan-tymoshenko commented on bench-duplicate.js
> +'use strict'
We don't need these benchmarks anymore.

2022-05-24 09:59 UTC, ivan-tymoshenko commented
<img width="743" alt="Снимок экрана 2022-05-24 в 12 59 08" src="https://user-images.githubusercontent.com/31734731/170005554-3c10fdd1-d230-4d86-a04f-0ed9c2d6be4c.png">

2022-05-24 11:25 UTC, mcollina approved these changes
lgtm

2022-05-24 12:53 UTC, merged