Add querrystring parser
delvedor/find-my-way pull request #284
Opened 2022-05-15 15:41 UTC by ivan-tymoshenko

We are already searching the querystring in the path and are spending some time on it. I want to pass the querystring to the handler instead of parsing it again in the handler. The querystring would be passed to the handler as a new argument.

The changes to the fastify:
https://github.com/ivan-tymoshenko/fastify/commit/00087f04117844ec7be7b23a9e2d0d8fe4b12e2c

Benchmarks:
In the main branch, I added a handler that parses querystring in the same way as fastify does 
(https://github.com/fastify/fastify/blob/0a4649f504bd466ce7dd37b510832746b213b2d4/lib/route.js#L377) and compared it with parsing a querystring natively in the find-my-way.

Handler in the main branch:

```js
  findMyWay.on(method, url, (req) => {
    const queryPrefix = req.url.indexOf('?')
    const query = querystring.parse(queryPrefix > -1 ? req.url.slice(queryPrefix + 1) : '')
    return query
  })
```

<img width="744" alt="Снимок экрана 2022-05-15 в 18 23 22" src="https://user-images.githubusercontent.com/31734731/168480888-a75a9ad8-a3f0-47a8-be73-8f70f7242a43.png">

2022-05-15 16:55 UTC, mcollina approved these changes
lgtm

2022-05-15 16:56 UTC, mcollina requested changes
could you update the docs?

2022-05-17 22:30 UTC, mcollina approved these changes
lgtm

2022-05-17 22:30 UTC, mcollina commented
Can you fix the conflicts?

2022-05-18 08:09 UTC, mcollina commented
Can you fix the conflicts?

2022-05-18 10:55 UTC, merged

2022-05-23 16:33 UTC, Uzlopak commented
Wow